[workspace]
members = ["crates/*"]
resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"

[profile.debug-lite]
inherits = "dev"
incremental = false
opt-level = 0
debug = 1
lto = "off"

[profile.release-lite]
inherits = "release"
opt-level = 2

[profile.debug-opt]
inherits = "release"
debug = 2
debug-assertions = true
incremental = true

[profile.docker]
inherits = "release"
# strip = "symbols" # Not supported in the workspace toolchain version

[patch.crates-io]
solana-transaction-status = { git = 'https://github.com/step-finance/solana.git', rev = "f8e999b8558f83b7807d3eff110796f6bd8b558a" }
solana-sdk = { git = 'https://github.com/step-finance/solana.git', rev = "f8e999b8558f83b7807d3eff110796f6bd8b558a" }
solana-geyser-plugin-interface = { git = 'https://github.com/step-finance/solana.git', rev = "f8e999b8558f83b7807d3eff110796f6bd8b558a" }
solana-logger = { git = 'https://github.com/step-finance/solana.git', rev = "f8e999b8558f83b7807d3eff110796f6bd8b558a" }
solana-program = { git = 'https://github.com/step-finance/solana.git', rev = "f8e999b8558f83b7807d3eff110796f6bd8b558a" }
solana-metrics = { git = 'https://github.com/step-finance/solana.git', rev = "f8e999b8558f83b7807d3eff110796f6bd8b558a" }
solana-zk-token-sdk = { git = 'https://github.com/step-finance/solana.git', rev = "f8e999b8558f83b7807d3eff110796f6bd8b558a" }
